### ISSUE TITLE
Nuove domande di teoria, esame sessione di luglio

### ISSUE THREAD

**Issue by GioLor33** [Pater999/UNITN-linguaggi-programmazione-SML#5]
Di seguito le domande nuove (rispetto al simulatore) presenti nella mia versione di esame di luglio. Non assicuro la correttezza delle risposte. Il simulatore io lo ho usato l'ultima volta l'11 luglio, quindi non so se alcune di queste siano già state inserite.

DOMANDA 1:
un ADT è definito essere un modello matematico di un user-defined type, insieme a tutte le operazioni <fill in> su quel modo:
1) **Struttura**
2) Primitiva
3) Assignment
4) Cardinalità
5) Nessuna delle precedenti

DOMANDA 2: 
un linguaggio di programmazione (come FORTRAN) usa una allocazione fissa della memoria (in compilazione). Questo tipo di linguaggio non può supportare:
1) Procedure
2) Eccezioni
3) **Ricorsione**
4) Nessuna della altre risposte
5) Numeri floating-point

DOMANDA 3:
il cut=! in Prolog:
1) **Ha successo e ferma backtracking**
2) Chiama un'eccezione
3) Esegue il backtracking
4) Fallisce e ferma il backtracking
5) Nessuna delle altre risposte

DOMANDA 4: [non sono sicura della risposta, so solo che non è sicuramente la 3]
in Prolog:
1) Conta l'ordine delle regole e predicati (da sinistra a destra) in una regola
2) Nessuna delle altre risposte
3) Conta l'ordine delle regole e predicati (da destra a sinistra) in una regola
4) Conta solo l'ordine delle regole
5) **Conta solo l'ordine dei predicati (da destra a sinistra) in una regola**

DOMANDA 5: [**non** è la 2]
si assuma che A sia un array di lunghezza 40. Trovare il 30simo elemento
1) Array.sub(A,30)
2) Array.sub(A,29)
3) Nessuna delle altre risposte
4) sub(A,29)
5) A[30]

----------------------------------------------------------------------------------------------------------------
Aggiungo di seguito alcune domande - sempre non inserite nel simulatore quando lo ho usato io - dell'appello di giugno che mi hanno mandato.

DOMANDA 6:
Memorizzare array in ordine di riga o colonna:
1) **Nessuna delle altre risposte**
2) Conta soltanto quando si usa il caching
3) Viene sempre usato l'ordine per colonna
4) Non conta mai
5) Viene sempre usato l'ordine per riga

DOMANDA 7:
Pointer reversal is used in garbage collection:
1) **To avoid wasting space for marking used records**
2) In implementations of Python
3) To deal with loops in pointer structures
4) When we don't have space for a earch structure
5) Nessuna delle altre risposte

DOMANDA 8:
In ML 4+3.0 genera come risultato:
1) **Errore di tipo**
2) 7.0
3) Nessuna delle altre risposte
4) Dipende dall'implementazione
5) 7

DOMANDA 9:
Dato il seguente programma ML:

`structure Struct1 = struct;
val i = 3;
type t = int;
val x = 4;
end;
signature SIG1 = sig;
val i:int;
type t;
val x: t;
end;
structure Struct2:> SIG1 = Struct1; `

Indicare il risultato di Struct2.x = Struct2.i;
1) Nessuna delle altre risposte
2) 3
4) false
5) **type error**
5) true

**Comment by Pater999** [comment]
Ciao grazie! Le ho aggiunte all'[altra repo](https://github.com/Pater999/UNITN-lingprog-simulatore-mod2) dove c'è il simulatore.
