### ISSUE TITLE
Esame giugno 2023

### ISSUE THREAD

**Issue by AleCornella** [Pater999/UNITN-linguaggi-programmazione-SML#8]
Ciao,
l'esame di quest'anno era nuovo, purtroppo non ho il testo esatto, ma dovrebbe essere una cosa del genere:

"""
scrivere una curried function “f” che prenda in input una lista di stringhe[ai, ai+1, …] e un intero n, e ritorni una lista di stringhe[bi, bi+1, …] in cui bi è uguale ad ai solo se la lunghezza di ai è minore o uguale ad n, altrimenti bi è uguale ad ai senza il primo carattere.

Esempio:
> \>f [" ", "ab", "abc", "abcd", "abcde"] 3;
val it = [" ", "ab", "abc", "bcd", "bcde"]: string list

"""

Questa è la mia soluzione che è stata considerata valida:

`fun f (nil) n = nil
| f (a::l) n = if (length (explode a) <= n)
                    then a::(f (l) n)
                    else implode(tl(explode(a)))::(f (l) n);
`

**Comment by Pater999** [comment]
Grazie lo ho aggiunto!
